### ISSUE TITLE
Header Files

### ISSUE THREAD

**Issue by dannluciano** [RoCampos/mo_algorithms#1]
Why you use only header files?

**Comment by RoCampos** [comment]
... to keep everything in single file, like spea2 in a single file spea2.h, multiobjective generic operation in a single file called multiobjective.h and so on.

I don't know if it cans reduce the efficiency. I don't know if the compiler will be consider the methods of the classes like inline method. 

In my tests I haven't felt any effect in efficiency, but we need more tests.
